language: python

notifications:
  email:
    - alkemic7+travis-ci-notifications@gmail.com

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install coverage
  - pip install coveralls
  - pip install nose
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=scrapper

after_success:
  - coveralls
