language: python

notifications:
  email:
    - alkemic7+travis-ci-notifications@gmail.com

python:
  - "2.7"

install:
  - pip install coverage
  - pip install coveralls
  - pip install nose
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=scrapper

after_success:
  - coveralls
